server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${root} # 데이터베이스 커넥션 이름
    password: ${db-password} # 데이터베이스 커넥션 비밀번호
    url: ${db-url}

  jpa:
    hibernate:
      ddl-auto: create-drop # 옵션은 필요에 따라 변경
    properties:
      hibernate:
        default_batch_fetch_size: 100 # 지연로딩 최적화를 위한 옵션
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  file:
    name: ${log-path} # slf4j를 사용할 때 생기는 로그 파일 경로
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  version: 1.6.8
  swagger-ui:
    # path: /swagger-ui.html
    disable-swagger-default-url: false
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs